name: Continuous integration

on: [pull_request, push]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version-file: '.nvmrc'

      - name: Create npm configuration
        run: echo "//npm.pkg.github.com/:_authToken=${token}" >> ~/.npmrc
        env:
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run test
